### ISSUE TITLE
String IID does not compile

### ISSUE THREAD

**Issue by kennethuil** [microsoft/com-rs#115]
Cargo.toml dependencies:
```
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "winreg", "winerror", "winnt"] }
com = "0.1.0"
```

main.rs:
```
use com::{com_interface, interfaces::iunknown::IUnknown};
use winapi::um::winnt::HRESULT;

#[com_interface("EFF8970E-C50F-45E0-9284-291CE5A6F771")]
pub trait IAnimal: IUnknown {
    fn eat(&self) -> HRESULT;
}

fn main() {
    println!("Hello, world!");
}
```

Result:
```
error: custom attribute panicked
 --> src\main.rs:4:1
  |
4 | #[com_interface("EFF8970E-C50F-45E0-9284-291CE5A6F771")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: IIDs must be exactly 36 characters long
```

Note: Removing the quotes from the GUID in the com_interface attribute causes it to compile successfully.

**Comment by nelsonjchen** [comment]
I have this problem too. But I think I know why. We referenced examples from the `master` of this repo. 

 #107 was merged in and it changed the API here to be non-`"`. The examples were updated and that usage isn't compatible with the `0.1.0` release on crates.io.

**Comment by rylev** [comment]
Hi! Thanks for reporting. Yes indeed, we need to release a new version of the crate. In the meantime, the right thing to do is to not use the `"`. Sorry for the inconvenience. Hopefully we'll have this fixed soon.
