### ISSUE TITLE
Passing com interfaces through ffi

### ISSUE THREAD

**Issue by zxey** [microsoft/com-rs#117]
I have c/c++ code that I want to convert gradually to Rust, the C/C++ code uses windows headers and uses com interfaces heavily, how do you pass compatible pointers to com interfaces between Rust and C/C++? When I try to do this the naive way, just passing *mut dyn IOleObject through ffi boundary, then rustc warns that interface is not ffi safe:
>warning: `extern` block uses type `dyn mshtml::IOleObject` which is not FFI-safe: trait objects have no C equivalent

Everything still compiles but my program crashes.

How do you do this correctly?

**Comment by kennethuil** [comment]
```
let obj: InterfaceRc<dyn mshtml::IOleObject> = ...;
let result = unsafe {PassComObj(obj.as_raw())};
// ...
```

**Comment by kennethuil** [comment]
The warning is calling out that a trait object pointers are actually two pointers (a "fat pointer"), and trying to pass that to C code absolutely will not work.

**Comment by rylev** [comment]
You most definitely cannot pass `InterfaceRc` across FFI boundaries. It's not even declared `repr(C)` which means it doesn't even have a stable representation in memory.

You should be able to call `InterfaceRc<dyn mshtml::IOleObject>::as_raw` to get a raw pointer representation. This pointer should be useable anywhere that a `*IOleObject` is needed in the C++ code. Does this not work?

**Comment by zxey** [comment]
Thank you, it works.
