### ISSUE TITLE
Decide how nullable com pointers should be modeled: `Option<ComPtr<T>>` or `ComPtr<T>`

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/com-rs#141]
In DirectX the pattern of using the `IID_PPV_ARGS` macro is very common, at the moment it's unclear how this should be mimicked with the new `com-rs` since one can't create an empty `ComPtr` and fill it in later it seems.

In C++ it's common to do something like this:

```
ComPtr<IDXGIFactory4> factory;
CreateDXGIFactory1(IID_PPV_ARGS(&factory));
```

**Comment by Jasper-Bekkers** [comment]
I maintain a crate that uses the old com-rs crate; it's a wrapper around the DirectXShaderCompiler called hassle-rs: https://github.com/Jasper-Bekkers/hassle-rs 

It's quite a frequent pattern there to start off with an empty/null ComPtr and have the API fill it in. Having to create a std::ptr::null_mut() first is a bit of a pain to use.

**Comment by Ciantic** [comment]
In the mean time, can someone give an example how to use nullable pointers especially with output argument?

E.g. if I have interface definition like:

```
HRESULT SomeMethod([In] IVirtualDesktop* inputDesktop, [Out] IVirtualDesktop** outputDesktop);
```

How would I write it? I'm experimenting with this:

```
    unsafe fn some_method(
        &self,
        input_desktop: ComPtr<dyn IVirtualDesktop>,
        output_desktop: ComPtr<dyn IVirtualDesktop>,
    ) -> HRESULT;
```
But it doesn't make sense to me, because the output type should be different from input type (**), should I use something like `*mut ComPtr<dyn IVirtualDesktop>` for the output type?

**Comment by Jasper-Bekkers** [comment]
@Ciantic I mostly stuck to the old com-rs because of this, since it wasn't really clear why this needed to change in the first place.

**Comment by Ciantic** [comment]
I figured out how I can use the output params at the moment, but sure enough it's a bit painful (Input params are easy, they are just given them as is, no example of those here).

```rust
   unsafe fn some_method(
        &self,
        output_desktop: *const *mut IVirtualDesktopVTable,
    ) -> HRESULT;
```

Next to use that param one must do like this:

```rust
let ptr: *mut IVirtualDesktopVTable = std::ptr::null_mut();
unsafe {
    let res = self.someinterface.some_method(&ptr);
}
let newptr: ComPtr<dyn IVirtualDesktop> = unsafe { ComPtr::new(ptr as *mut _) };
let newrc: ComRc<dyn IVirtualDesktop> = ComRc::new(f);
```

**Comment by rylev** [comment]
`ComRc` takes ownership of `ptr` while `ComPtr` represents merely a borrow. We're re-examining the design of the crate to make this more clear. In this case, you can also pass a `ComPtr<dyn IVirtualDesktop>` as the argument to `some_method` as `ComPtr`s are FFI safe.

**Comment by Ciantic** [comment]
I'm trying to wrap this to my head. If I minimize the usage of `ComPtr`, as I have done now.  It should now be able to make de-allocations to occur normally because I now use mostly just `ComRc` in my interface definitions.

However replacing `*const *mut IVirtualDesktopVTable` with `ComPtr<dyn IVirtualDesktop>` does not work because you can't create null `ComPtr`, right?

E.g.

```
  unsafe fn some_method(
        &self,
        output_desktop: *const ComPtr<dyn IVirtualDesktop>,
    ) -> HRESULT;
```

And then 

```
        let ptr: ComPtr<dyn IVirtualDesktop> = unsafe { ComPtr::new(std::ptr::null_mut()) };
        let res = unsafe { self.some_method(&ptr) };
        // handle error
        let rc: ComRc<dyn IVirtualDesktop> = ptr.upgarde();
```

Type checks just fine! But it throws panic 😒: 

> thread 'main' panicked at 'ComPtr's ptr was null'

Because isn't the whole point that you *can* not create null ptrs with ComPtr at the moment?

Thanks.

**Comment by rylev** [comment]
`Option<ComPtr<dyn Interface>>` is exactly equivalent to `*mut *const Interface::VTable`. So if you need to initialize from a null, pass in a `None`.

**Comment by Ciantic** [comment]
Oh my goodness! It works!

```
    unsafe fn get_current_desktop(
        &self,
        outDesktop: *const Option<ComPtr<dyn IVirtualDesktop>>,
    ) -> HRESULT;
```

```rust
let ptr: Option<ComPtr<dyn IVirtualDesktop>> = None;
let res = unsafe {
            self.virtual_desktop_manager_internal
                .get_current_desktop(&ptr)
        };
let result: ComRc<dyn IVirtualDesktop> = ptr.unwrap().upgrade();
```

This was not obvious to me.

**Comment by rylev** [comment]
This is something that may change in the next version of the crate. If it stays like this, we will make sure to more explicitly document this pattern.

**Comment by rylev** [comment]
A more correct version of this is (notice the use of `&mut`):

```rust
let mut ptr: Option<ComPtr<dyn IVirtualDesktop>> = None;
let res = unsafe {
            self.virtual_desktop_manager_internal
                .get_current_desktop(&mut ptr)
        };
let result: ComRc<dyn IVirtualDesktop> = ptr.unwrap().upgrade()
```

It's technically UB to write to an immutable reference.

**Comment by Ciantic** [comment]
I noticed that I can also use ComRc directly!

```rust
    unsafe fn get_current_desktop(
        &self,
        outDesktop: *const Option<ComRc<dyn IVirtualDesktop>>,
    ) -> HRESULT;
```

```rust
        let mut ptr: Option<ComRc<dyn IVirtualDesktop>> = None;
        let res = unsafe {
            self.virtual_desktop_manager_internal
                .get_current_desktop(&mut ptr)
        };
```

Should I use ComRc directly in my Interface definitions? It seems more convenient, because I don't have to upgrade.

**Comment by rylev** [comment]
Yes that should work.

**Comment by rylev** [comment]
As of right now, we are going with Option<IInterface>. Closing this.
