### ISSUE TITLE
co_class macro breaks the struct lifetime declaration

### ISSUE THREAD

**Issue by Ciantic** [microsoft/com-rs#151]
Try following:

```rust
#[co_class(implements(IVirtualDesktopNotification))]
pub struct VirtualDesktopChangeListener<'a> {
    x: &'a i32,
}
```

When I compile I get error:

```
error[E0261]: use of undeclared lifetime name `'a`
  --> src\changelistener.rs:33:9
   |
32 | pub struct VirtualDesktopChangeListener<'a> {
   |                                        - help: consider introducing lifetime `'a` here: `<'a>`
33 |     x: &'a i32,
   |         ^^ undeclared lifetime
```

It's complaining that the lifetime is missing, even though it's right there where it thinks it should be.

Is co_class macro removing the lifetime declarations for some reason?

**Comment by rylev** [comment]
Can you run [`cargo expand` ](https://github.com/dtolnay/cargo-expand) on your crate and post the output here?

**Comment by Ciantic** [comment]
Lot of stuff. But I think it's this one:

```
 #[repr(C)]
    pub struct VirtualDesktopChangeListener {
        __ivirtualdesktopnotificationvptr:
            *const <dyn IVirtualDesktopNotification as com::ComInterface>::VTable,
        __refcnt: std::cell::Cell<u32>,
        x: &'a i32,
        service: Arc<Cell<Option<ComRc<dyn IVirtualDesktopNotificationService>>>>,
        cookie: Arc<Cell<u32>>,
        _on_desktop_change: RefCell<Option<Box<OnDesktopChange>>>,
        _on_desktop_created: RefCell<Option<Box<OnDesktopCreated>>>,
        _on_desktop_destroyed: RefCell<Option<Box<OnDesktopDestroyed>>>,
        _on_window_change: RefCell<Option<Box<OnDesktopWindowChange>>>,
    }
```

**Comment by rylev** [comment]
Looks like indeed we're not respecting lifetime (or probably any generic) parameters.

**Comment by rylev** [comment]
After thinking about this, I'm not sure what to do. Having your COM class tied to some lifetime is unlikely to be correct as COM classes must be heap allocated and will live for an indeterminate period of time (however long there are outstanding interface handles to it). If you're tying your COM class to some lifetime you won't be able to give out interface handles to it. Perhaps I'm missing something?

**Comment by Ciantic** [comment]
Yes, I circumvented this somehow already.
