### ISSUE TITLE
COM registration only works if the server dll is named "server.dll"

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/com-rs#157]
See title. If your server library is named anything other than "server", registration with `regsvr32.exe` appears to work, but it actually doesn't register the correct dll, and any attempt to create an instance of a COM object fails with HRESULT=800401f9.  

It looks like the dll name is hardcoded here: https://github.com/microsoft/com-rs/blob/74dbe3019e5f046976b7fd22fc367fd798734a56/src/registration.rs#L140

**Comment by rylev** [comment]
Whoops. Good catch. Will fix this!
