### ISSUE TITLE
Questions: oleaut32.dll

### ISSUE THREAD

**Issue by konghk78** [microsoft/com-rs#158]
Hello, there

When I tried to open com object by using com-rs, I got the access violation 
exit code: 0xc0000005, STATUS_ACCESS_VIOLATION
And when I debug this logic, I saw that the pointer from create_instance is mapped to oleaut32.dll.

![image](https://user-images.githubusercontent.com/52471448/87437984-4a24c200-c5ef-11ea-95d5-7ced6482d20b.png)

Could you give me a hint how I can use this properly?

BR
Heejin Jeong

**Comment by rylev** [comment]
Hey there. Can you post a minimal reproduction of this issue? It's hard to tell what's going on from a screenshot. Thanks!

**Comment by konghk78** [comment]
Hello
I dig into more and seem the the file I want to is written in ActiveX technology. Would it be possible to use com-rs for accessing active x ctrl?
Br
Heejin
