### ISSUE TITLE
[Help] Some newbie questions on converting an IDL

### ISSUE THREAD

**Issue by vpopescu** [microsoft/com-rs#179]
I'm experimenting with converting an IDL, and I have some newbies questions, They may be too obvious, but I haven't been able to find the answers poking around the code.

1. Are attributes such as '[dual](https://docs.microsoft.com/en-us/windows/win32/midl/dual)' and '[nonextensible](https://docs.microsoft.com/en-us/windows/win32/midl/nonextensible)' supported or implied in any way?

2. How would I go about creating a free-threaded COM server?

3. Also, how should I represent some of the more windows-specific types such as VARIANTs and BSTRs?

Hoping that IDL tool will materialize soon 👍 

Thanks in advance!

**Comment by rylev** [comment]
👋Hello! 
 
> Are attributes such as 'dual' and 'nonextensible' supported or implied in any way?

No

> How would I go about creating a free-threaded COM server?

We don't explicitly support Multithreaded apartments. This is something I need to think more about. 

> Also, how should I represent some of the more windows-specific types such as VARIANTs and BSTRs?

This is being addressed in #182

**Comment by heaths** [comment]
@vpopescu in the meantime, if it helps, see https://github.com/heaths/vssetup-rs/blob/master/src/bstr.rs. It's not full-featured and only contains what I need for this project (for now), but hopefully might help you until a more complete solution is available here.

**Comment by vpopescu** [comment]
Thank you both. I will close the request, since this answers my question.
