### ISSUE TITLE
winapi interfaces interoperability

### ISSUE THREAD

**Issue by DataTriny** [microsoft/com-rs#180]
Hello,

I need to define COM objects that implement COM interfaces that I can pass to functions declared by the winapi crate.

Let's pretend that winapi defines a function and an interface like:

```rust
fn DoStuff(pRetVal: *mut *mut ISomeInterface) -> HRESULT;

RIDL!{#[uuid(...)]
interface ISomeInterface(ISomeInterfaceVtbl): IUnknown(IUnknownVtbl) {
	fn GetValue(
		pRetVal: *mut u8,
	) -> HRESULT,
}}
```

Because winapi doesn't provide an easy way to implement interfaces for objects, I would like to use this crate to help me deal with virtual table management.

So I tried re-defining the interface above using the `com::interface!` macro:

```
com::interfaces! {
	#[uuid("...")]
	pub unsafe interface ISomeInterface: IUnknown {
		pub fn get_value(
			&self,
			p_ret_val: *mut u8
		) -> HRESULT;
	}
}

com::class! {
	pub class MyObject: ISomeInterface {
		value: u8
	}
	
	impl ISomeInterface for MyObject {
		fn get_value(&self, p_ret_val: *mut u8) -> HRESULT {
			unsafe { *p_ret_val = self.value; };
			NOERROR
		}
	}
}
```

And convert it to its winapi counterpart:

```
let o = MyObject::allocate(10);
let mut i = o.query_interface::<ISomeInterface>().unwrap();
let p_i: *mut ISomeInterface = &mut i;
let p = p_i as *mut c_void;
let p_wi = p as *mut crate::winapi_interfaces::ISomeInterface;
let v: *mut u8 = null_mut();
(*p_wi).GetValue(v);
```

But it always fail at runtime:

```
error: process didn't exit successfully: `target\debug\comtest.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

I have checked that all three pointers point to the same memory address, I have used the `-Zprint-type-sizes` flag to make sure that the memory layout of both versions of the interface are the same.

The only differences I can see are the name of both virtual table field (which I don't think matter), and the calling convention of the virtual table functions (`stdcall` for com, `system` for winapi, so it could differ).

What am I doing wrong? Since I am a beginner with COM, does my conversion code even make sence?

Many thanks.

Best regards.

**Comment by MarijnS95** [comment]
Hey!

Two small things:
- `ISomeInterface` from com-rs contains an `inner:` field which is a pointer to `ISomeInterfaceVPtr`, this again is a pointer to the actual vtable (`ISomeInterfaceVTable`). You need to interpret `i` as `*mut ISomeInterface` instead of taking the address of it.
- You pass a `null_mut()` into `GetValue`, which will in turn dereference that in `*p_ret_val`. Instead consider passing:
  ```rust
  let mut v = 0u8;
  (*p_wi).GetValue(&mut v as *mut _)
  ```

That should get the segfaults solved. Consider using `cargo-expand` (or browse the com-rs source code!) to see the layout of generated structures and/or a powerful debugger like `gdb` that can deal with Rust struct formats and inspect their layout (and pointer values!) accordingly.

**Comment by DataTriny** [comment]
Hi, here is an updated version of my code that seems to work:

```rust
let o = MyObject::allocate(10);
let mut i = o.query_interface::<ISomeInterface>().unwrap();
let p_i: *mut ISomeInterface = &mut i;
let p = p_i as *mut c_void;
let p_wi = p as *mut *mut crate::winapi_interfaces::ISomeInterface;
let mut v = 0u8;
(**p_wi).GetValue(&mut v as *mut _);
println!("{}", v);
```

Thank you @MarijnS95  for your help, the `null_mut` pointer was of course stupid, but I somewhat missed the double indirection for the virtual table.

I also agree with you on the winapi part and I expressed my concerns on retep998/winapi-rs#867.

Regards.

**Comment by MarijnS95** [comment]
@DataTriny Awesome, glad I could help!

Note that these casts/transmutes are undefined behaviour unless the interface struct is marked as `repr(C)` or `repr(transparent)`. Perhaps com-rs should attain an `.as_raw()` function to take the `inner` object pointer out for exactly these usecases, until the whole com-rs/winapi "thingy" is unified?

**Comment by rylev** [comment]
@MarijnS95 all the wrapper structs in com-rs are `#[repr(transparent)]` so they can be treated just like the underlying pointers. Or did I miss a case?

**Comment by MarijnS95** [comment]
@rylev Ah never mind I was looking at the wrong line, the interface is indeed `repr(transparent)`:

https://github.com/microsoft/com-rs/blob/dd7c97b322256f9eebea7c2c64106138e4561cf8/macros/support/src/interface/interface.rs#L26-L29

Sorry for that. Still, would it make sense to have a way to pull this pointer out without casts/transmutes?

@DataTriny In that case it's probably more natural to write `let p_wi: *mut ISomeInterface = unsafe { std::mem::transmute(i) };`.

**Comment by DataTriny** [comment]
@MarijnS95  I initially used `std::mem::transmute` but as I understand, it copies the data. Given the fact that com-rs interfaces are pinned, and so should not be moved, wouldn't it cause me trouble?

**Comment by rylev** [comment]
@DataTriny. `std::mem::transmute` copies the ptr itself (not the data it points to) and forgets the previous value. This is effectively a move of the pointer and is totally fine to do.

**Comment by DataTriny** [comment]
Makes sence. Thanks @rylev for clarifying.
