### ISSUE TITLE
com or com-rs , which one to use?

### ISSUE THREAD

**Issue by oldoldman** [microsoft/com-rs#185]
I found com-rs is marked as deprecated at cargo.io and com is recommended, but the example in the cover page of this repo is com-rs. So which one is recommended ? Many thanks!

**Comment by rylev** [comment]
This repo is for the [`com`](https://crates.io/crates/com) crate, and has nothing to do with the `com-rs` crate. The repo name and the name of the crate don't have to match. We called this repo `com-rs` so that it is easy to tell that this is a Rust repo.
