### ISSUE TITLE
Incorrect CLSID registry key generation

### ISSUE THREAD

**Issue by Laegluin** [microsoft/com-rs#189]
I'm not exactly experienced when it comes to COM but shouldn't the registry keys for CLSIDs be enclosed in braces? At the moment, the `inproc_dll_module!` macro does not add them and the classes cannot be found:

https://github.com/microsoft/com-rs/blob/master/src/production/registration.rs#L141-L149

**Comment by MarijnS95** [comment]
Looks like these disappeared with https://github.com/microsoft/com-rs/commit/3fa2dfe0aca2d1f2ddbb2fbe8ed0ae728f772a9b
