### ISSUE TITLE
Interfaces nested more than 2 levels deep do not compile

### ISSUE THREAD

**Issue by russcam** [microsoft/com-rs#208]
The [documentation for producing a COM component states](https://github.com/microsoft/com-rs#producing-a-com-component):

> Specify each of the interfaces the class implements. You must list the interface's parent interface in paraenthesis with the exception of IUnknown which is assumed when no parent is specified (e.g., : `MyInterface(MyParentInterface(MyGrandParentInterface))), MyOtherInterface`

When attempting to specify an interface _hierarchy_ more than two levels deep, for example,

```rust
com::class! {
    pub class CorProfiler: ICorProfilerCallback3(ICorProfilerCallback2(ICorProfilerCallback)), ICorProfiler {
            profiler_info: Cell<Option<ICorProfilerInfo>>
     }
}
```

compilation fails with

> error: impl for a non-declared interface
>    --> src\classes\cor_profiler_callback.rs:145:10
>        |
> 145 |     impl ICorProfilerCallback for CorProfiler {
>        |   

Two levels deep works fine, but more than two results in a compiler error.

**Comment by rokit** [comment]
Did this break again? I'm also getting `impl for a non-declared interface` error when trying to implement a three-interface hierarchy with `com = {version = "0.4.0", features = ["production"]}`.
