### ISSUE TITLE
Question: How do I get interface vptr from a struct?

### ISSUE THREAD

**Issue by lokanchung** [microsoft/com-rs#213]
Hi,
I'm trying to return 'self' as interface pointer.
I'm trying to do something equivalent to this C++ code.

```cpp
IEatable* Animal::GetEatable() {
    return this;
} 
```
where Animal implements multiple interfaces. In this case, C++ took care of returning correct vptr.

 I haven't found a good, clean way to do it in Rust other than refering to a member created by proc macro.
```Rust
// this is not working code
impl Animal for IEatable {
    fn GetEatable(&self) -> *mut c_void {
        *self.__ieatablevptr as *mut cvoid
    }
}
```
Is there any macro or function that finds out proper vptr from struct instance? 
Any help would be appreciated. Thank you.

**Comment by rylev** [comment]
You could call `Interface::as_raw`:

```rust
impl Animal for IEatable {
    fn GetEatable(&self) ->  core::ptr::NonNull<core::ptr::NonNull<IEatable::VTable>> {
        self.as_raw()
    }
}
```

**Comment by lokanchung** [comment]
Sadly I'm using old, forked version which doesn't have `as_raw()`, but now I know which part I should look into. Thank you!
