### ISSUE TITLE
How to use com-rs?

### ISSUE THREAD

**Issue by raavimohindar** [microsoft/com-rs#217]
I have pulled the repository and started build using 

### cargo build --all-targets --all-features --release

and it has created a directory called ..\target\release\deps

In my project I have inserted these two lines at the top,

### init_runtime().expect("Failed to initialize COM Library");
and ran
### rustc my_prog.rs --extern com=libcom-*.rlib

Compiler error:
 init_runtime().expect("Failed to initialize COM Library");
 |             ^ expected one of `!` or `::`

Sorry, I lack the start and any help will be much appreciated.

**Comment by rylev** [comment]
Hello! It seems you're missing a main function in your project. If you're new to Rust, COM might be a poor place to learn the language. I would suggest giving [The Rust Programming Language book](https://doc.rust-lang.org/book/) a read, and when you've done that, checking out the examples in the `examples` folder of this repo.

**Comment by Rike-cz** [comment]
@rylev Are the examples up to date? I have bunch of errors, mainly `could not find class in com` (but interfaces macro of the same origin works good). Maybe some simple standalone example would help, please.
