### ISSUE TITLE
Aggregation Design improvements

### ISSUE THREAD

**Issue by adrianwithah** [microsoft/com-rs#47]
Currently, the aggregation API is not as idiomatic. Some problems include:

- Ability to get the aggregated object's interface pointer is not yet implemented.

- If an aggregate exposes IAnimal, ICat, IDomesticAnimal, the user is exposed to 3 different set_aggregate functions. Ideally we want to cut down to 1 per aggregated object.

- The top level macro `#[co_class]` and `#[aggr_co_class]` must be the first macro defined, before any `com_implements` or `aggr` attributes. Ideally, we want to combine all into a single macro.

- Create safe wrapper for instantiating an aggregated object through `CoCreateInstance`. Currently, there's no way of obtaining the existing `Runtime` instance.

- Store aggregated object as a `ComPtr`, instead of a `*mut IUnknownVPtr`

Edit: Adding on from #58 , it is not immediately obvious what you need to pass as the second type parameter in `create_aggregated_instance`.

**Comment by rylev** [comment]
We no longer support aggregation
