### ISSUE TITLE
Consider writing GUIDs as strings in attribute macros

### ISSUE THREAD

**Issue by chris-morgan** [microsoft/com-rs#90]
```rust
#[com_interface(EFF8970E-C50F-45E0-9284-291CE5A6F771)]
pub trait IAnimal: IUnknown { … }
```

This makes me uncomfortable. I’m half-expecting a formatter to reformat the GUID as `EFF8970E - C50F -45E0 -9284 -291CE5A6F771` or similar (rustfmt won’t now but could conceivably in the future), and some syntax highlighters *will* highlight parts of it differently, e.g. “9284” as a number but the rest not. Also, if lower-case hex is used (no idea whether it’s supported in theory or not), then some GUIDs will fail to tokenise, e.g. segments `0bd5` and `1ef3` won’t compile (invalid binary literal and invalid exponent, respectively).

I would prefer the GUID to be a string:

```rust
#[com_interface("EFF8970E-C50F-45E0-9284-291CE5A6F771")]
pub trait IAnimal: IUnknown { … }
```

`#[com_interface = "…"]` would also work.

**Comment by m-hilgendorf** [comment]
>Also, if lower-case hex is used (no idea whether it’s supported in theory or not), then some GUIDs will fail to tokenise, e.g. segments 0bd5 and 1ef3 won’t compile (invalid binary literal and invalid exponent, respectively).

Ran into this problem. It's not lower case hex either, e.g 

```rust
use com::com_interface;
use com::interfaces::iunknown::IUnknown;

#[com_interface(000000EA-0000-0000-0000-000000000000)]
pub trait Broken: IUnknown {}
```

will fail with `error: expected at least one digit in exponent`.  What's interesting is that the macro actually expands correctly. 

A quick and dirty fix for this is to change `macros/support/src/com_interface/iids` to the following

```
  pub fn generate(macro_attr: &TokenStream, interface_ident: &Ident) -> HelperTokenStream {
--      let iid_value = macro_attr.to_string().replace(' ', "");
++    let mut iid_value = macro_attr.to_string().replace(' ', "");
++    if iid_value.starts_with('\"') && iid_value.ends_with('\"') {
++        iid_value = iid_value[1..iid_value.len()-1].to_string();
++    }
```

**Comment by rylev** [comment]
These are definitely fair points. I think we can move to using string literals instead. Thanks for reporting!
