### ISSUE TITLE
docs.rs build

### ISSUE THREAD

**Issue by pravic** [microsoft/com-rs#91]
Right now it fails to compile, see https://docs.rs/crate/com/0.1.0/builds/188898. 

I believe, there should be a way to satisfy docs.rs in the same way as winapi crate does.

https://docs.rs/winapi/0.3.8/winapi/

https://github.com/retep998/winapi-rs/blob/0.3/Cargo.toml#L15

**Comment by rylev** [comment]
Thanks for reporting this! Yep, looks like we need to constrain to Windows.

**Comment by mominul** [comment]
The build is failing again https://docs.rs/crate/com/0.1.0/builds/188898

**Comment by pravic** [comment]
@mominul It's just hasn't been published since then.
