### ISSUE TITLE
Example for creating objects locally and returning these by interface

### ISSUE THREAD

**Issue by Rantanen** [microsoft/com-rs#96]
I was trying to look through the examples, but couldn't find a way to implement something similar to:

https://github.com/Rantanen/intercom/blob/15d8af0d22114ebf619513293b79dfa1e7613973/test/testlib/src/return_interfaces.rs#L18-L20

I got as far as constructing the `CreatedClass` with `CreatedClass::allocate(..)`, but got stuck turning it into `ICreatedClass` in a safe way. The only approach I found was going through the raw `query_interface` API, such as:

```rust
let s = CreatedClass::allocate(..);
s.add_ref();
let rc = unsafe {
    let mut ptr : *mut winapi::ctypes::c_void = std::ptr::null_mut();
    s.query_interface(
        &IID_ICREATEDCLASS as *const _,
        &mut ptr as *mut _,);

    com::InterfaceRc::<dyn ICreatedClass>::new(
        unsafe { com::InterfacePtr::new(ptr) }
    )
};
```

Encountered this as part of my benchmarking effort for Intercom. Current results show Intercom as an order of magnitude slower for simple method calls, with com-rs managing four COM calls (and their simple implementation) in 10 ns/iteration while Intercom spends 66 ns/iteration on them (135ns/iter after introducing logging, but not using it). Makes me re-consider whether I should put logging in Intercom behind a non-default feature.

Then again, a struct that does nothing but `set`/`add`/`get` a `u32` value into a `Cell<u32>` is a bit extreme benchmark... :)

**Comment by rylev** [comment]
Thanks for reporting this! I believe it is not currently possible to turn a concrete co class into an interface through a safe API. We should probably generate the `get_interface` same wrapper that's on `InterfaceRc`. Of course, PRs are always welcome, but I'll label this as an improvement.

Out of curiosity - what was the reason you needed to treat your co class as an interface?

**Comment by Rantanen** [comment]
In this specific case it was just benchmarking, but I've encountered that specific need in the past frequently when I've had the need to return a COM interface from another method call.

```rust
impl IInterface for CoOneClass {
    fn method(&self, out: *mut InterfacePtr<IAnotherInterface>) -> HRESULT {

        // CoAnotherClass might not even be publicly constructible by having no CLSID.
        let another_class = CoAnotherClass::allocate(self.a + self.b);

        // Need to somehow convert the constructed CoAnotherClass into an interface
        // pointer of IAnotherInterface.
        *out = InterfacePtr::from(another_class);
        NOERROR
    }
}
```

**Comment by kennethuil** [comment]
In the opening example, the object will get destroyed as soon as s goes out of scope, regardless of the refcount.  The generated XXXClassFactory::create_instance adds a mem::forget to prevent that from happening.

For now, I'm just calling XXXClassFactory::create_instance.

**Comment by simonbuchan** [comment]
I'm trying to host `WebBrowser` (the IE web view OLE class), porting the C logic that's in the `web-view-sys` crate so I have better control over security, capturing navigations, etc. (I'm trying to get single-sign on credentials).

I don't think this crate is going to cut it in it's current state, but this is a good exercise of it. For this issue, you have to provide `IOleObject::SetClientSite` an implementation of `IOleClientSite` to give it a host window, which it will then spider out from to a few dozen different interfaces for various callbacks and customization hooks. You don't want your web view host to be registered for someone else to call, so ideally you wouldn't have a factory or CLSID at all. Windows has lots of other APIs like this where passing a purely in-proc interface is how you customize it.
